[package]
name = "cmsis-dsp"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.68.1"
# Fork is necessary pending merge of https://github.com/rust-lang/cmake-rs/pull/187
cmake = { git = "https://github.com/frankplow/cmake-rs", branch = "system-name-generic" }
